pe-and-platform/puppetserver-nightly:
  PreBuild:
    - make lint
  Build:
    - make build PUPPERWARE_ANALYTICS_STREAM=production-nightly
    - make test
  AfterBuildSuccess:
    - docker login -u "$DISTELLI_DOCKER_USERNAME" -p "$DISTELLI_DOCKER_PW" "$DISTELLI_DOCKER_ENDPOINT"
    - make publish
