version: '3.5'

services:
  puppet:
    # NOTE: if this service changes, global shared definition should be updated
    # https://github.com/puppetlabs/pupperware/blob/main/gem/lib/pupperware/compose-services/puppet.yml
    hostname: puppet
    image: ${PUPPET_TEST_DOCKER_IMAGE:-puppet/puppetserver}
    expose:
      - 8141
    environment:
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPET_MASTERPORT=8141
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-false}
      - USE_PUPPETDB=false

  compiler:
    hostname: compiler
    image: ${PUPPET_TEST_DOCKER_IMAGE:-puppet/puppetserver}
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-false}
      - PUPPETSERVER_HOSTNAME=compiler
      - CA_ENABLED=false
      - CA_HOSTNAME=puppet
      - CA_MASTERPORT=8141
      - USE_PUPPETDB=false

networks:
  default:
    name: puppetserver_test
